development:
  adapter: postgresql
  host: localhost
  username: kelly
  password: kelly
  database: phonebuzz
  port: 5432

test:
  adapter: postgresql
  database: phonebuzz
  pool: 5
  username: kelly
  password: kelly
  port: 5432

production:
  adapter: postgresql
  database: phonebuzz
  pool: 5
  username: kelly
  password: kelly
  port: 5432
