development:
  adapter: postgresql
  database: phonebuzz
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>
  host: localhost

test:
  adapter: postgresql
  host: localhost
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>
  database: phonebuzz
