default: &default
  adapter: postgresql
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>
  host: localhost
  pool: 5

development:
  <<: *default
  database: development

test:
  <<: *default
  database: test
