default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  adapter: postgresql
  encoding: unicode
  database: development
  pool: 5
  host: localhost

test:
  adapter: postgrsql
  encoding: unicode
  database: phonebuzz
  pool: 5
  host: localhost
