default: &default
  adapter: postgresql
  pool: 5

development:
  <<: *default
  database: phonebuzz
  host: localhost

test:
  <<: *default
  database: phonebuzz

production:
  <<: *default
  database: phonebuzz
